name: Deploy to Hostingername: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      - name: Deploy to Hostinger
        uses: appleboy/scp-action@master
        with:
          host: ssh -p 65002 u973484608@82.180.175.77 # Replace with your Hostinger server address
          username: u973484608 # Replace with your Hostinger SSH username
          password: ${{ secrets.Ask123456 }} # Use the correct secret name without special characters
          source: "build/"
          target: "/hawar-app" # Replace with the path to your website's public_html folder on Hostinger
