name: Deploy to Hostinger

on: 
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
        
    - name: Deploy to Hostinger
      env:
        HOST: ${{ secrets.HOST }} 
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no -p 65002 "$USER"@"$HOST" << EOF
        cd path/to/react-app
        rm -rf * 
        scp -P 65002 -r ./build/* "$USER"@"$HOST":~/path/to/react-app        
        EOF
