name: Deploy to Hostinger

on:
  push:
    branches:
      - masterjobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          host: ssh -p 65002 u973484608@82.180.175.77 # Replace with your Hostinger server address
          username: u973484608 # Replace with your Hostinger SSH username
          password: ${{ secrets.Ask123456 }} # Use the correct secret name without special characters
          source: "build/"
          target: "/public_html/hawar-app" # Replace with the path to your website's public_html folder on Hostinger
